### ISSUE TITLE
depsAreEqual() flaw

### ISSUE THREAD

**Issue by yairopro** [peterjuras/use-state-with-deps#131]
Hi @peterjuras 

Nice project, but there's a flaw in you dependencies check.

https://github.com/peterjuras/use-state-with-deps/blob/6f8467501ae28f445c8127b45c9e5b46bf1291e6/src/deps-are-equal.ts#L5

Because you only check up to `prevDeps.length`the following case won't re-initialize the state:
```typescript
// 1st render
useStateWithDeps(() => ..., [1]);

// next render
useStateWithDeps(() => ..., [1, 2]); // won't reinitialize
```

You should check up to the max length of both deps.
https://github.com/yairopro/js-tools/blob/981d355f5371244844ee02bf28cab9b7208d501b/array/match/index.js#L14

Still, a huge thank you for your shared work.

**Comment by peterjuras** [comment]
I think that's debatable :) In my view, yes it should change, since the dependencies array is no longer the same and the dependencies have been updated.

Having no value in an array compared with `undefined` in another array is not equal to me. In general, I'm not sure how many people have varying lengths for dependency arrays.

**Comment by yairopro** [comment]
> I think that's debatable. 

Yes of course. 
The debat here seems to be: **Is the length of the array itself part of the dependencies ?**
To me, it's just a container. Only the values it brings are important. 
[That's actually a feature request on react](https://github.com/facebook/react/issues/18229) which means react itself currently thinks like you. 😁

>  I'm not sure how many people have varying lengths for dependency arrays.  

Such use case happened to me very very few times. The most repeated case I had was with a simple list-ui with filters to apply when fetching the items.

```typescript
// some struct to fetch as list
interface Item {
	state: number,
}

// List props
interface Props {
	/* The list will fetch only items with state included in this array. */
	includedStates: number[], 
}

function List({includedStates}: Props){
	// we refetch a new list of items with the filter applied here...

	// and we reset the `endReached` state
	const [endReached, setEndReached] = useStateWith(false, includeFields);
}
```

Prop such as `includedStates` here  can come from various flow and is not bounded to any fixed length.
Sometimes it's the user who toggle any state he wants to include in the list.
